# Generated by Django 3.2.9 on 2021-12-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_writer',
        ),
    ]
