# Generated by Django 3.2.9 on 2021-12-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_report_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_requestor_user', to='reports.reportuser'),
        ),
    ]
