# Generated by Django 3.2.9 on 2021-12-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_report_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_writer_user', to='reports.reportuser'),
        ),
    ]
