# Generated by Django 3.2.9 on 2022-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_report_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
